import glob

imports_to_add = ""
struct_fields = ""
insert_calls = ""

rs_files = glob.glob("src/obj*")

for rs_file_name in rs_files:
    rs_file = open(rs_file_name, "r")
    rs_content = rs_file.read()

    start = "@start_room_object_info"
    end = "@end_room_object_info"

    index1 = rs_content.find(start)
    index2 = rs_content.find(end, index1 + len(start))

    obj_info_string = rs_content[index1 + len(start):index2].strip("\n// ")
    fields = obj_info_string.split(",")
    json_name = fields[0]
    struct_name = fields[1]
    mod_name = rs_file_name.replace("src/", "").replace(".rs", "") 

    imports_to_add += mod_name + "::" + struct_name + ",\n"
    struct_fields += "pub " + json_name + ": Option<Vec<" + struct_name + ">>,\n"
    insert_calls += "insert_from_list(self." + json_name + ", area_name, map);\n"
    
    

print("""// GENERATED BY room_obj_load_generator.py

use std::{collections::HashMap, sync::Arc};

use serde::{Deserialize, Serialize};

use crate::{
    IMPORTS_TO_ADD
    traits_for_obj::{FileToInGame, Obj},
};

#[derive(Serialize, Deserialize, Debug)]
pub struct RoomObjectsFromFile {
    STRUCT_FIELDS
}

impl RoomObjectsFromFile {
    pub fn insert_all(self, area_name: &str, map: &mut HashMap<String, Vec<Arc<dyn Obj>>>) {
        fn insert_from_list<T: FileToInGame>(
            list: Option<Vec<T>>,
            area_name: &str,
            map: &mut HashMap<String, Vec<Arc<dyn Obj>>>,
        ) {
            if let Some(items) = list {
                for item in items {
                    let coords = item.room_coords();
                    let room = format!("{}_{}", coords.x, coords.y);
                    map.entry(room)
                        .or_insert_with(Vec::new)
                        .push(item.to_obj(area_name));
                }
            }
        }
        INSERT_CALLS    
    }
}
""".replace("IMPORTS_TO_ADD", imports_to_add).replace("STRUCT_FIELDS", struct_fields).replace("INSERT_CALLS", insert_calls))
