// GENERATED BY room_obj_load_generator.py

use std::{collections::HashMap, sync::Arc};

use serde::{Deserialize, Serialize};

use crate::{
    obj_checkpoint::CheckpointFromFile,
    obj_door::DoorFromFile,
    obj_npc::NpcFromFile,
    traits_for_obj::{FileToInGame, Obj},
};

#[derive(Serialize, Deserialize, Debug)]
pub struct RoomObjectsFromFile {
    pub checkpoints: Option<Vec<CheckpointFromFile>>,
    pub npcs: Option<Vec<NpcFromFile>>,
    pub doors: Option<Vec<DoorFromFile>>,
}

impl RoomObjectsFromFile {
    pub fn insert_all(self, area_name: &str, map: &mut HashMap<String, Vec<Arc<dyn Obj>>>) {
        fn insert_from_list<T: FileToInGame>(
            list: Option<Vec<T>>,
            area_name: &str,
            map: &mut HashMap<String, Vec<Arc<dyn Obj>>>,
        ) {
            if let Some(items) = list {
                for item in items {
                    let coords = item.room_coords();
                    let room = format!("{}_{}", coords.x, coords.y);
                    map.entry(room)
                        .or_insert_with(Vec::new)
                        .push(item.to_obj(area_name));
                }
            }
        }
        insert_from_list(self.checkpoints, area_name, map);
        insert_from_list(self.npcs, area_name, map);
        insert_from_list(self.doors, area_name, map);
    }
}
